name: PR Build

on:
  pull_request:
    branches: [ main, dev, qa, release ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to test'
        required: true
        default: 'dev'
        type: string

concurrency:
  group: main-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: "Detect Changed Projects"
    runs-on: ubuntu-latest
    outputs:
      app-changed: ${{ steps.changes.outputs.app_files_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get modified files
        id: modified-files
        uses: tj-actions/changed-files@v46

      - name: Detect changed projects
        id: changes
        env:
          ALL_MODIFIED_FILES: ${{ steps.modified-files.outputs.all_modified_files }}
        run: |
          app_files_changed=false
          for file in ${ALL_MODIFIED_FILES}; do
            if [[ $file =~ src/.* ]] || [[ $file == "*.js" ]] || [[ $file == "*.py" ]] || [[ $file == ".github/workflows/app-ci.yml" ]]; then
              app_files_changed=true
            fi
          done
          echo "app_files_changed=$app_files_changed"
          echo "app_files_changed=$app_files_changed" >> "$GITHUB_OUTPUT"

  app-ci:
    name: "App CI"
    needs: detect-changes
    if: needs.detect-changes.outputs.app-changed == 'true'
    uses: ./.github/workflows/app-ci.yml

  build-result:
    name: "Build Result"
    runs-on: ubuntu-latest
    needs: [detect-changes, app-ci]
    if: always()
    steps:
      - name: Evaluate PR Build Result
        run: |
          app_result="${{ needs.app-ci.result }}"
          
          if [[ "$app_result" == "failure" ]]; then
            echo "❌ Failed: App CI"
            exit 1
          fi
          
          echo "✅ PR build complete"
